# -*- coding: utf-8 -*-
from PyQt5 import QtWidgets, QtCore
from Ui.AVDC_new import Ui_MainWindow  # 导入由pyuic5生成的UI文件


class AVDC_Main_UI(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        # 初始化UI
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # setup about page
        self.setup_about_page()
        self.show()

    def setup_about_page(self):
        _translate = QtCore.QCoreApplication.translate
        self.ui.textBrowser_about.setHtml(
            _translate(
                "AVDV",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:20pt; font-weight:600;">AVDC</span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:14pt; font-weight:600;">目录</span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="#_一、功能简介"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">一、功能简介</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="#_二、项目简介"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">二、项目简介</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="#_三、常见番号命名参考"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">三、常见番号命名参考</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="#_设置说明"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">四、设置说明</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600;"> </span></p>\n'
                '<h1 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="_一、功能简介"></a><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">一</span><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">、功能简介</span></h1>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  日本电影</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">元数据抓取工具</span><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">/刮削器，配合本地影片管理软件</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">EMBY,KODI，PLEX</span><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">等管理本地影片，该软件起到分类与元数据抓取作用，利用元数据信息来分类，供本地影片</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">分类整理</span><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">使用。</span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;"> </span></p>\n'
                '<h1 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="_二、项目简介"></a><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">二</span><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">、项目简介</span></h1>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt;">Gui made by </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">moyy996</span><span style=" font-family:\'宋体\'; font-size:12pt;">，Core made by </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">yoshiko2</span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt;">tg官方电报群:</span><a href="https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ"><span style=" font-family:\'宋体\'; font-size:12pt; text-decoration: underline; color:#0000ff;"> </span></a><a href="https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt;">命令行版项目地址：</span><a href="https://github.com/yoshiko2/AV_Data_Capture"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">https://github.com/yoshiko2/AV_Data_Capture</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt;">GUI版项目地址：</span><a href="https://github.com/moyy996/AVDC"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">https://github.com/moyy996/AVDC</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt;">GUI版EXE下载地址：</span><a href="https://github.com/moyy996/AVDC/releases"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">https://github.com/moyy996/AVDC/releases</span></a></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt;"> </span></p>\n'
                '<h1 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="_三、常见番号命名参考"></a><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">三</span><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">、常见番号命名参考</span></h1>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">不区分大小写、刮削前尽量命名规范！！！！</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">1、标准有码</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Javdb、Javbus:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">SSNI-111</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Dmm：</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">ssni00111</span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">2、无码</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Javdb、Javbus、Avsox:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">111111-1111、111111_111、HEYZO-1111、n1111</span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">3、素人</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Mgstage:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">259LUXU-1111</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Javdb:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">LUXU-1111</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Fc2club:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">FC2-111111、FC2-PPV-111111、FC2PPV-111111</span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4、欧美</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">Javdb、Javbus:</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">sexart.11.11.11(系列.年.月.日)</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;"> </span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">5、自带字幕影片</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">可以把电影命名为类似</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">ssni-xxx-c.mp4</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">,</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">ssni-xxx-C.mp4</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">，</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">abp-xxx-CD1-C.mp4 </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">的规则。</span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">6、多集影片</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">可以把多集电影按照集数后缀命名为类似</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">ssni-xxx-cd1.mp4</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">, </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">ssni-xxx-cd2.mp4</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">, </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">abp-xxx-CD1-C.mp4</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">的规则，只要含有</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">-CDn/-cdn</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">类似命名规则，即可使用分集功能.**不支持-A -B -1 -2,容易跟字幕的-C混淆**.</span></h4>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">7、多集、字幕顺序</span></h4>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">abp-xxx-CD1-C.mp4</span><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">，</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">分集在前，字幕在后</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">，</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">字幕必须与拓展名靠近</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">，-</span><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;">C.mp4</span><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">.</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">8、外挂字幕文件</span></h4>\n'
                '<h4 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">字幕文件名</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">必须与</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">影片文件名</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">一致，才可以一起移动到新目录，目前支持</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;">srt ass sub</span><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">类型的字幕文件。</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;"> </span></p>\n'
                '<h1 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="_设置说明"></a><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">四</span><span style=" font-family:\'宋体\'; font-size:22pt; font-weight:600;">、设置说明</span></h1>\n'
                "<h1 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'宋体'; font-size:22pt; font-weight:600;\"><br /></h1>\n"
                '<h1 style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#24292e; background-color:#ffffff;">详细的说明： </span><a href="https://github.com/moyy996/AVDC/blob/master/README.md"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;">https://github.com/moyy996/AVDC/blob/master/README.md</span></a></h1>\n'
                "<h1 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'宋体'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\"><br /></h1>\n"
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.1.刮削模式/整理模式</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">1、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">刮削模式</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">：通过番号刮削数据，包括元数据、封面图、缩略图、背景图。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">2、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">整理模式</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">：仅根据女优把电影命名为番号并分类到女优名称的文件夹下。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.2.软链接模式：使用此模式，要以管理员身份运行。</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">刮削完不移动视频，而是在相应目录</span><span style=" font-family:\'宋体\'; font-size:10.5pt; color:#ff0000;">创建软链接</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（类似于快捷方式），方便PT下载完既想刮削又想继续上传的仓鼠党同志。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">但是，只能在媒体库展示，不</span><span style=" font-family:\'宋体\'; font-size:10.5pt; color:#ff0000;">能在媒体库播放</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.3.调试模式</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">输出番号的元数据，包括封面，导演，演员，简介等。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.4.排除目录</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">在多层目录刮削时</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">排除所填目录</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.5.视频目录</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">要整理的视频的目录，会遍历此目录下的所有视频，</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">包括子目录</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">中。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.6.命名规则</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">1、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">目录命名</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">：存放视频数据的目录名，支持</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">多层目录</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，支持</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">自定义符号</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，例：[actor]/studio/number-【title】。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">2、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">视频标题</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（媒体库中）：</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">nfo</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">中的标题命名。例：number-[title]。可以自定义符号。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">3、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">视频标题</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（本地文件）：本地视频、图片的命名。例：number-[title]。可以自定义符号。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">4、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">可选项</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">为</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">title</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（片名）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">actor</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（演员）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">studio</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（制作商）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">director</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（导演）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">release</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（发售日）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">year</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（发行年份）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">number</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（番号）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">runtime</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（时长）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">series</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（系列）、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">publisher</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（发行商）</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.7.代理设置</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;">(1).代理</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">proxy=127.0.0.1:1080</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">proxy行设置</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">本地代理地址和端口</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，支持Shadowxxxx/X,V2XXX本地代理端口，代理软件开</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">全局模式</span><span style=" font-family:\'宋体\'; font-size:10.5pt;"> ,建议使用</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">日本代理</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">如果一直报Connect Failed! Please check your Proxy or Network!错误，请</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">检查端口号</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">是否正确，或者把proxy=后面的地址和端口</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">删除</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，并开启代理软件</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">全局模式</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，或者重启电脑，代理软件，网卡。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;">(2).连接超时重试设置</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">timeout=10 </span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">10为超时重试时间 单位：秒，可选范围3-10</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;">(3).连接重试次数设置</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">retry=3 </span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">3即为重试次数，可选范围2-5</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.8.媒体库选择</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">如果是PLEX，请安装插件：</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">XBMCnfoMoviesImporter</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.9.排除指定字符和目录，字符串</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">1、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">排除字符</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">:指定字符删除，例如排除字符： \\()，删除</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">创建文件夹时</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">的\\()字符</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">2、</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">排除目录</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">:指定目录，例如排除目录： failed,JAV_output，多目录刮削时</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">跳过</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">failed,JAV_output</span></p>\n'
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'宋体'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:'宋体'; font-size:10.5pt;\">3、</span><span style=\" font-family:'宋体'; font-size:10.5pt; font-weight:600; color:#ff0000;\">排除字符串</span><span style=\" font-family:'宋体'; font-size:10.5pt;\">:提取番号时，先删除指定字符串，提高成功率，字符串之间用','隔开。</span></p>\n"
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.10.网站选择</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">可以使用</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">所有网站</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，或者</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">指定网站</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">（</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">avsox,javbus,dmm,javdb,fc2club，mgstage</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">）进行刮削。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">仅使用javdb进行刮削，</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">尽量不要用</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，刮削30左右会被JAVDB</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">封IP</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">一段时间。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.11.保存日志</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">开启后日志保存在</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">程序目录的Log目录下</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">的txt文件内，每次运行会产生一个txt文件，txt文件</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">可以删除</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，不影响程序运行。</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:12pt; font-weight:600;">4.12.失败后移动文件</span></h4>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;">  </span><span style=" font-family:\'宋体\'; font-size:10.5pt;">如果刮削不到影片信息，</span><span style=" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;">可选择不移动视频</span><span style=" font-family:\'宋体\'; font-size:10.5pt;">，或者自动移动到失败输出目录中。</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;"> </span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'宋体\'; font-size:10.5pt;"> </span></p></body></html>',
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    window = AVDC_Main_UI()
    sys.exit(app.exec_())
